export const data = [
  { id: "1", name: "Ayesha Khan", message: "Rescheduled Influenza vaccine appointment", time: "12:15 AM", avatarUrl: "/diverse-person-portrait.png", selected: true },
  { id: "2", name: "Imran Ali", message: "Marked Hepatitis B vaccine as Completed", time: "12:20 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "3", name: "Sarah Ahmad", message: "Logged Influenza vaccine.", time: "12:25 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "4", name: "Usman Tariq", message: "Updated Measles vaccine record", time: "12:30 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "5", name: "Fatima Noor", message: "Scheduled appointment for Polio vaccine", time: "12:35 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "6", name: "Ali Raza", message: "Marked Tetanus vaccine as Completed", time: "12:40 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "7", name: "Zainab Malik", message: "Logged Yellow Fever vaccine", time: "12:45 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "8", name: "Hamza Yousaf", message: "Rescheduled appointment for COVID-19 booster", time: "12:50 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "9", name: "Maryam Bibi", message: "Completed Diphtheria vaccine", time: "12:55 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "10", name: "Bilal Hussain", message: "Updated Polio vaccine appointment", time: "1:00 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "11", name: "Sana Qureshi", message: "Marked Influenza booster as Completed", time: "1:05 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "12", name: "Danish Ahmed", message: "Rescheduled Hepatitis A vaccine", time: "1:10 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "13", name: "Laiba Sheikh", message: "Logged Typhoid vaccine.", time: "1:15 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "14", name: "Umar Farooq", message: "Scheduled appointment for HPV vaccine", time: "1:20 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "15", name: "Hira Ali", message: "Marked COVID-19 vaccine as Completed", time: "1:25 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "16", name: "Fawad Khan", message: "Logged Chickenpox vaccine.", time: "1:30 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "17", name: "Nadia Hassan", message: "Rescheduled Rabies vaccine", time: "1:35 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "18", name: "Saad Iqbal", message: "Updated appointment for Measles vaccine", time: "1:40 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "19", name: "Mariam Javed", message: "Completed Influenza booster", time: "1:45 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "20", name: "Rehan Shah", message: "Logged Hepatitis B vaccine.", time: "1:50 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "21", name: "Iqra Malik", message: "Scheduled appointment for Tetanus vaccine", time: "1:55 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "22", name: "Adnan Rafiq", message: "Marked COVID-19 booster as Completed", time: "2:00 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "23", name: "Bushra Aslam", message: "Logged Typhoid vaccine.", time: "2:05 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "24", name: "Junaid Arif", message: "Rescheduled Polio vaccine appointment", time: "2:10 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "25", name: "Kiran Fatima", message: "Completed Chickenpox vaccine", time: "2:15 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "26", name: "Rashid Khan", message: "Updated Measles vaccine record", time: "2:20 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "27", name: "Mahnoor Ali", message: "Marked Influenza vaccine as Completed", time: "2:25 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "28", name: "Shahzaib Tariq", message: "Logged Diphtheria vaccine.", time: "2:30 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "29", name: "Anum Zafar", message: "Rescheduled Yellow Fever vaccine", time: "2:35 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "30", name: "Tariq Jameel", message: "Scheduled appointment for Rabies vaccine", time: "2:40 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "31", name: "Fiza Khan", message: "Marked Typhoid vaccine as Completed", time: "2:45 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "32", name: "Shahid Anwar", message: "Updated appointment for COVID-19 booster", time: "2:50 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "33", name: "Eman Rauf", message: "Logged Influenza vaccine.", time: "2:55 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "34", name: "Nouman Zia", message: "Completed Measles vaccine", time: "3:00 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "35", name: "Amna Khalid", message: "Rescheduled appointment for Polio vaccine", time: "3:05 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "36", name: "Omer Sheikh", message: "Marked Diphtheria vaccine as Completed", time: "3:10 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "37", name: "Rimsha Qazi", message: "Scheduled appointment for Chickenpox vaccine", time: "3:15 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "38", name: "Hassan Raza", message: "Updated Rabies vaccine record", time: "3:20 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "39", name: "Sadia Imtiaz", message: "Logged Tetanus vaccine.", time: "3:25 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "40", name: "Muneeb Asad", message: "Completed Yellow Fever vaccine", time: "3:30 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "41", name: "Zoya Khalid", message: "Rescheduled Influenza vaccine appointment", time: "3:35 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "42", name: "Asim Qadir", message: "Marked Hepatitis B vaccine as Completed", time: "3:40 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "43", name: "Maliha Tariq", message: "Logged Polio vaccine.", time: "3:45 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "44", name: "Farhan Ali", message: "Scheduled appointment for Typhoid vaccine", time: "3:50 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "45", name: "Sehar Khan", message: "Updated appointment for Influenza booster", time: "3:55 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "46", name: "Talha Javed", message: "Completed COVID-19 vaccine", time: "4:00 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "47", name: "Areeba Noor", message: "Rescheduled Measles vaccine", time: "4:05 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "48", name: "Kashif Hussain", message: "Marked Rabies vaccine as Completed", time: "4:10 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "49", name: "Sumbal Niazi", message: "Logged Hepatitis A vaccine.", time: "4:15 AM", avatarUrl: "/diverse-person-portrait.png" },
  { id: "50", name: "Raza Shah", message: "Scheduled appointment for COVID-19 booster", time: "4:20 AM", avatarUrl: "/diverse-person-portrait.png" }
]
